CREATE DATABASE QL_SHOP_GIAY_DU_AN_1
IF OBJECT_ID('KHACHHANG') IS NOT NULL
   DROP TABLE KHACHHANG
GO
   CREATE TABLE KHACHHANG
(
   MAKHACHHANG NVARCHAR(50) NOT NULL,
   HOTEN NVARCHAR(50) NULL,
   SODT NVARCHAR(15) NULL,
   DIACHI NVARCHAR(100) NULL,
   EMAIL NVARCHAR(50) NULL
   CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKHACHHANG)
)
IF OBJECT_ID('NHANVIEN') IS NOT NULL
   DROP TABLE NHANVIEN
GO
   CREATE TABLE NHANVIEN
(
   MANHANVIEN NVARCHAR(50) NOT NULL,
   HOTEN NVARCHAR(50) NULL,
   NGAYSINH DATETIME NULL,
   DIACHI NVARCHAR(100) NULL,
   MATKHAU NVARCHAR (50) NULL,
   VAITRO BIT NULL,
   SODT NVARCHAR(15) NULL,
   TRANGTHAI BIT NULL
   CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANHANVIEN)
)
IF OBJECT_ID('SIZE') IS NOT NULL
   DROP TABLE SIZE
GO
   CREATE TABLE SIZE
(
   MASIZE NVARCHAR(50) NOT NULL,
   SOSIZE INT NULL
   CONSTRAINT PK_SIZE PRIMARY KEY (MASIZE)
)
IF OBJECT_ID('MAU') IS NOT NULL
   DROP TABLE MAU
GO
   CREATE TABLE MAU
(
   MAMAU NVARCHAR(50) NOT NULL,
   TENMAU NVARCHAR(50) NULL
   CONSTRAINT PK_MAU PRIMARY KEY (MAMAU)
)
IF OBJECT_ID('CHATLIEU') IS NOT NULL
   DROP TABLE CHATLIEU
GO
   CREATE TABLE CHATLIEU
(
   MACHATLIEU NVARCHAR(50) NOT NULL,
   CHATLIEU NVARCHAR(50) NULL
   CONSTRAINT PK_CHATLIEU PRIMARY KEY (MACHATLIEU)
)
IF OBJECT_ID('HANG') IS NOT NULL
   DROP TABLE HANG
GO
   CREATE TABLE HANG
(
   MAHANG NVARCHAR(50) NOT NULL,
   TENHANG NVARCHAR(50) NULL
   CONSTRAINT PK_HANG PRIMARY KEY (MAHANG)
)
IF OBJECT_ID('LOAI') IS NOT NULL
   DROP TABLE LOAI
GO
   CREATE TABLE LOAI
(
   MALOAI NVARCHAR(50) NOT NULL,
   TENLOAI NVARCHAR(50) NULL
   CONSTRAINT PK_LOAI PRIMARY KEY (MALOAI)
)
IF OBJECT_ID('NOISANXUAT') IS NOT NULL
   DROP TABLE NOISANXUAT
GO
   CREATE TABLE NOISANXUAT
(
   MANOISANXUAT NVARCHAR(50) NOT NULL,
   TENNOISANXUAT NVARCHAR(50) NULL
   CONSTRAINT PK_NOISANXUAT PRIMARY KEY (MANOISANXUAT)
)
IF OBJECT_ID('HINHANH') IS NOT NULL
   DROP TABLE HINHANH
GO
   CREATE TABLE HINHANH
(
   MAHINHANH NVARCHAR(50) NOT NULL,
   TENHINHANH NVARCHAR(50) NULL
   CONSTRAINT PK_HINHANH PRIMARY KEY (MAHINHANH)
)
IF OBJECT_ID('SANPHAM') IS NOT NULL
   DROP TABLE SANPHAM
GO
   CREATE TABLE SANPHAM
(
   MASANPHAM NVARCHAR(50) NOT NULL,
   TENDANHMUC NVARCHAR(50) NULL
   CONSTRAINT PK_SANPHAM PRIMARY KEY (MASANPHAM)
)
IF OBJECT_ID('KHUYENMAI') IS NOT NULL
   DROP TABLE KHUYENMAI
GO
   CREATE TABLE KHUYENMAI
(
   MAKHUYENMAI NVARCHAR(50) NOT NULL,
   TENKHUYENMAI NVARCHAR(50) NULL,
   LOAIGIAMGIA BIT NULL,
   MUCGIAMGIA NVARCHAR(50) NULL,
   THOIGIANBATDAU DATETIME NULL,
   THOIGIANKETTHUC DATETIME NULL,
   TRANGTHAI NVARCHAR (100) NULL
   CONSTRAINT PK_KHUYENMAI PRIMARY KEY (MAKHUYENMAI)
)
IF OBJECT_ID('SANPHAMKHUYENMAI') IS NOT NULL
   DROP TABLE SANPHAMKHUYENMAI
GO
   CREATE TABLE SANPHAMKHUYENMAI
(
   MASANPHAMKHUYENMAI NVARCHAR(50) NOT NULL,
   MASANPHAM NVARCHAR(50) NULL,
   MAKHUYENMAI NVARCHAR(50) NULL,
   TRANGTHAI NVARCHAR(50) NULL
   CONSTRAINT PK_SANPHAMKHUYENMAI PRIMARY KEY (MASANPHAMKHUYENMAI),
   CONSTRAINT FK_SANPHAM_SANPHAMKHUYENMAI FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM,
   CONSTRAINT FK_KHUYENMAI_SANPHAMKHUYENMAI FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI
)
IF OBJECT_ID('SANPHAM_CHITIET') IS NOT NULL
   DROP TABLE SANPHAM_CHITIET
GO
   CREATE TABLE SANPHAM_CHITIET
(
   MASANPHAM_CHITIET NVARCHAR(50) NOT NULL,
   MASANPHAM NVARCHAR(50) NULL,
   MASIZE NVARCHAR (50) NULL,
   MAMAU NVARCHAR (50) NULL,
   MACHATLIEU NVARCHAR (50) NULL,
   MAHANG NVARCHAR (50) NULL,
   MALOAI NVARCHAR (50) NULL,
   MANOISANXUAT NVARCHAR (50) NULL,
   MAHINHANH NVARCHAR (50) NULL,
   TENSANPHAM_CHITIET NVARCHAR(100) NULL,
   GIATIEN MONEY NULL,
   GIANHAP MONEY NULL,
   SOLUONG INT NULL,
   MOTA NVARCHAR (200) NULL,
   TRANGTHAI BIT NULL
   CONSTRAINT PK_SANPHAM_CHITIET PRIMARY KEY (MASANPHAM_CHITIET),
   CONSTRAINT FK_SANPHAM_SANPHAM_CHITIET FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM,
   CONSTRAINT FK_SIZE_SANPHAM_CHITIET FOREIGN KEY (MASIZE) REFERENCES SIZE,
   CONSTRAINT FK_MAU_SANPHAM_CHITIET FOREIGN KEY (MAMAU) REFERENCES MAU,
   CONSTRAINT FK_CHATLIEU_SANPHAM_CHITIET FOREIGN KEY (MACHATLIEU) REFERENCES CHATLIEU,
   CONSTRAINT FK_HANG_SANPHAM_CHITIET FOREIGN KEY (MAHANG) REFERENCES HANG,
   CONSTRAINT FK_LOAI_SANPHAM_CHITIET FOREIGN KEY (MALOAI) REFERENCES LOAI,
   CONSTRAINT FK_NOISANXUAT_SANPHAM_CHITIET FOREIGN KEY (MANOISANXUAT) REFERENCES NOISANXUAT,
   CONSTRAINT FK_HINHANH_SANPHAM_CHITET FOREIGN KEY (MAHINHANH) REFERENCES HINHANH
)
IF OBJECT_ID('HOADON') IS NOT NULL
   DROP TABLE HOADON
GO
   CREATE TABLE HOADON
(
   MAHOADON NVARCHAR(50) NOT NULL,
   MANHANVIEN NVARCHAR(50) NULL,
   MAKHACHHANG NVARCHAR(50) NULL,
   NGAYTAO DATETIME NULL,
   NGAYTHANHTOAN DATETIME NULL,
   TONGTIEN MONEY NULL,
   TIENLAI MONEY NULL,
   HINHTHUCTHANHTOAN BIT NULL,
   GHICHU NVARCHAR (200) NULL,
   TRANGTHAI BIT NULL
   CONSTRAINT PK_HOADON PRIMARY KEY (MAHOADON),
   CONSTRAINT FK_NHANVIEN_HOADON FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN,
   CONSTRAINT FK_KHACHHANG_HOADON FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG
)
IF OBJECT_ID('HOADON_CHITIET') IS NOT NULL
   DROP TABLE HOADON_CHITIET
GO
   CREATE TABLE HOADON_CHITIET
(
   MAHOADON_CHITIET NVARCHAR(50) NOT NULL,
   MAHOADON NVARCHAR(50) NULL,
   MASANPHAM_CHITIET NVARCHAR(50) NULL,
   SOLUONG INT NULL,
   GIATIEN MONEY NULL
   CONSTRAINT PK_HOADON_CHITIET PRIMARY KEY (MAHOADON_CHITIET),
   CONSTRAINT FK_HOADON_HOADONCHITET FOREIGN KEY (MAHOADON) REFERENCES HOADON,
   CONSTRAINT FK_SANPHAM_CHITIET_HOADON_CHITIET FOREIGN KEY (MASANPHAM_CHITIET) REFERENCES SANPHAM_CHITIET
)
----Dữ Liệu
INSERT INTO NHANVIEN VALUES('NV01', N'DƯƠNG NAM KHÁNH', '07/10/2001', N'HÀ NỘI', 123456789, '1', '0987826481', '1'),
                            ('NV02', N'DƯƠNG TIẾN HUY', '04/05/2003', N'HÀ NỘI', 123456789, '0', '0963521492', '1'),
							('NV03', N'ĐỖ TIẾN HƯNG', '05/04/2002', N'HẢI PHÒNG', 123456789, '0', '0963521493', '1'),
							('NV04', N'DƯƠNG VĂN TUẤN', '07/06/2003', N'QUẢNG NINH', 123456789, '0', '0963521494', '1')
SELECT*FROM NHANVIEN

INSERT INTO SIZE VALUES('S01', 35),
                       ('S02', 36),
                       ('S03', 37),
					   ('S04', 38),
					   ('S05', 39),
					   ('S06', 40),
					   ('S07', 41),
					   ('S08', 42),
					   ('S09', 43),
					   ('S10', 44)
SELECT*FROM SIZE